import { Channel, Contact, Conversation, UserSettings, BlockedUser } from "@/types";

export const initialSettings: UserSettings = {
  theme: "dark",
  density: "cozy",
  enterToSend: true,
  desktopNotifications: true,
  soundNotifications: true,
  displayName: "Alex Morgan",
  statusMessage: "Focusing on ChatFlow v2.0 release 🚀",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  email: "alex.morgan@chatflow.io",
  role: "Lead Product Designer",
  presence: "online",
};

export const initialBlockedUsers: BlockedUser[] = [
  {
    id: "block-1",
    name: "Spam Bot 4000",
    handle: "@bot_deals",
    avatar: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80",
    blockedDate: "Sep 12, 2026",
  },
  {
    id: "block-2",
    name: "Crypto Promoter",
    handle: "@moon_gains",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    blockedDate: "Aug 29, 2026",
  },
];

export const initialContacts: Contact[] = [
  {
    id: "contact-1",
    name: "Sarah Jenkins",
    role: "Staff Software Engineer",
    email: "sarah.j@chatflow.io",
    presence: "online",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    bio: "Distributed systems, web performance, and open source fanatic.",
    customStatus: "Reviewing pull requests 💻",
    conversationId: "c1",
  },
  {
    id: "contact-2",
    name: "Marcus Chen",
    role: "Frontend Architect",
    email: "marcus.c@chatflow.io",
    presence: "online",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    bio: "Design systems, Next.js, and accessible UI patterns.",
    customStatus: "Building shadcn component library ✨",
    conversationId: "c2",
  },
  {
    id: "contact-3",
    name: "Elena Rostova",
    role: "UX Research Lead",
    email: "elena.r@chatflow.io",
    presence: "away",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    bio: "User advocacy, behavioral research, and usability testing.",
    customStatus: "Conducting user interviews 🎧",
    conversationId: "c3",
  },
  {
    id: "contact-4",
    name: "David Kim",
    role: "Principal Product Manager",
    email: "david.k@chatflow.io",
    presence: "offline",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    bio: "Roadmaps, quarterly targets, metrics, and team operations.",
    customStatus: "Out of office until Monday 🌴",
    conversationId: "c4",
  },
  {
    id: "contact-5",
    name: "Priya Sharma",
    role: "VP of Engineering",
    email: "priya.s@chatflow.io",
    presence: "online",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    bio: "Scaling teams, architectural integrity, and developer velocity.",
    customStatus: "In all-hands sync 📊",
    conversationId: "c5",
  },
  {
    id: "contact-6",
    name: "Lucas Vance",
    role: "Site Reliability Engineer",
    email: "lucas.v@chatflow.io",
    presence: "offline",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    bio: "Kubernetes, observability, low latency edge delivery.",
    customStatus: "On-call rotation 🛠️",
  },
];

export const initialConversations: Conversation[] = [
  {
    id: "c1",
    name: "Sarah Jenkins",
    type: "direct",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    presence: "online",
    lastMessage: "I just deployed the new WebSocket handler to staging. Can you test the reactions?",
    lastMessageTime: "10:42 AM",
    unreadCount: 2,
    description: "Direct message with Sarah Jenkins (Staff Software Engineer)",
    sharedMedia: [
      { id: "m1", name: "websocket-benchmarks.pdf", type: "file", size: "2.4 MB", date: "Sep 18, 2026" },
      { id: "m2", name: "architecture-v2.png", type: "image", size: "1.1 MB", url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=300&auto=format&fit=crop&q=80", date: "Sep 17, 2026" },
      { id: "m3", name: "https://github.com/chatflow/core-service/pull/482", type: "link", date: "Sep 16, 2026" },
    ],
    messages: [
      {
        id: "msg-1-1",
        senderId: "contact-1",
        senderName: "Sarah Jenkins",
        senderAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
        content: "Hey Alex! Do you have a moment to review the revised conversation latency specs?",
        timestamp: "10:30 AM",
        date: "Today",
        isSentByMe: false,
        reactions: [{ emoji: "👍", count: 1, reactedByMe: true }],
      },
      {
        id: "msg-1-2",
        senderId: "user-me",
        senderName: "Alex Morgan",
        content: "Morning Sarah! Yes absolutely, pulling up the dashboard right now.",
        timestamp: "10:32 AM",
        date: "Today",
        isSentByMe: true,
        status: "read",
      },
      {
        id: "msg-1-3",
        senderId: "user-me",
        senderName: "Alex Morgan",
        content: "The optimistic UI rendering makes message delivery feel instantaneous. Sub-50ms roundtrip!",
        timestamp: "10:35 AM",
        date: "Today",
        isSentByMe: true,
        status: "read",
        reactions: [{ emoji: "🔥", count: 2 }],
      },
      {
        id: "msg-1-4",
        senderId: "contact-1",
        senderName: "Sarah Jenkins",
        senderAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
        content: "Awesome! We shaved off another 15ms by pipelining the presence heartbeats.",
        timestamp: "10:40 AM",
        date: "Today",
        isSentByMe: false,
      },
      {
        id: "msg-1-5",
        senderId: "contact-1",
        senderName: "Sarah Jenkins",
        senderAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
        content: "I just deployed the new WebSocket handler to staging. Can you test the reactions?",
        timestamp: "10:42 AM",
        date: "Today",
        isSentByMe: false,
        reactions: [
          { emoji: "🎉", count: 1 },
          { emoji: "🚀", count: 2, reactedByMe: true },
        ],
      },
    ],
  },
  {
    id: "c2",
    name: "Marcus Chen",
    type: "direct",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    presence: "online",
    lastMessage: "The shadcn Dialog and ScrollArea components work seamlessly together.",
    lastMessageTime: "9:15 AM",
    unreadCount: 0,
    description: "Direct message with Marcus Chen (Frontend Architect)",
    sharedMedia: [
      { id: "m2-1", name: "theme-tokens.json", type: "file", size: "12 KB", date: "Sep 17, 2026" },
      { id: "m2-2", name: "https://ui.shadcn.com/docs/components", type: "link", date: "Sep 15, 2026" },
    ],
    messages: [
      {
        id: "msg-2-1",
        senderId: "contact-2",
        senderName: "Marcus Chen",
        senderAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
        content: "Hey Alex, I checked the token mappings in globals.css. Everything adheres to standard HSL variables.",
        timestamp: "9:10 AM",
        date: "Today",
        isSentByMe: false,
      },
      {
        id: "msg-2-2",
        senderId: "contact-2",
        senderName: "Marcus Chen",
        senderAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
        content: "The shadcn Dialog and ScrollArea components work seamlessly together.",
        timestamp: "9:15 AM",
        date: "Today",
        isSentByMe: false,
        reactions: [{ emoji: "🙌", count: 1, reactedByMe: true }],
      },
    ],
  },
  {
    id: "c3",
    name: "Elena Rostova",
    type: "direct",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    presence: "away",
    lastMessage: "Users loved the compact density toggle in our latest usability session!",
    lastMessageTime: "Yesterday",
    unreadCount: 0,
    description: "Direct message with Elena Rostova (UX Research Lead)",
    sharedMedia: [
      { id: "m3-1", name: "september-usability-report.pdf", type: "file", size: "4.8 MB", date: "Sep 17, 2026" },
    ],
    messages: [
      {
        id: "msg-3-1",
        senderId: "contact-3",
        senderName: "Elena Rostova",
        senderAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
        content: "Hi Alex! Synthesizing feedback from our 12 usability interview sessions.",
        timestamp: "4:15 PM",
        date: "Yesterday",
        isSentByMe: false,
      },
      {
        id: "msg-3-2",
        senderId: "contact-3",
        senderName: "Elena Rostova",
        senderAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
        content: "Users loved the compact density toggle in our latest usability session!",
        timestamp: "4:20 PM",
        date: "Yesterday",
        isSentByMe: false,
        reactions: [{ emoji: "❤️", count: 3 }],
      },
      {
        id: "msg-3-3",
        senderId: "user-me",
        senderName: "Alex Morgan",
        content: "That is fantastic news. We'll make sure it's accessible directly in Settings.",
        timestamp: "4:25 PM",
        date: "Yesterday",
        isSentByMe: true,
        status: "read",
      },
    ],
  },
  {
    id: "c4",
    name: "Product Design Guild",
    type: "group",
    avatar: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=150&auto=format&fit=crop&q=80",
    lastMessage: "David: Sprint review is locked for 2 PM GMT.",
    lastMessageTime: "Yesterday",
    unreadCount: 5,
    membersCount: 14,
    description: "Cross-functional design systems, specs, and design review guild.",
    sharedMedia: [
      { id: "m4-1", name: "chatflow-brand-guidelines.pdf", type: "file", size: "8.2 MB", date: "Sep 16, 2026" },
      { id: "m4-2", name: "https://figma.com/@chatflow-design-system", type: "link", date: "Sep 14, 2026" },
    ],
    messages: [
      {
        id: "msg-4-1",
        senderId: "contact-4",
        senderName: "David Kim",
        senderAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
        content: "Reminder to everyone: Please update your Figma links before tomorrow's review.",
        timestamp: "2:00 PM",
        date: "Yesterday",
        isSentByMe: false,
      },
      {
        id: "msg-4-2",
        senderId: "contact-4",
        senderName: "David Kim",
        senderAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
        content: "David: Sprint review is locked for 2 PM GMT.",
        timestamp: "2:05 PM",
        date: "Yesterday",
        isSentByMe: false,
        reactions: [{ emoji: "👍", count: 4 }],
      },
    ],
  },
  {
    id: "c5",
    name: "Engineering Core Team",
    type: "group",
    avatar: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=150&auto=format&fit=crop&q=80",
    lastMessage: "Priya: All service monitors are green across US-East and EU-Central.",
    lastMessageTime: "Sep 16",
    unreadCount: 0,
    membersCount: 28,
    description: "Architecture, infrastructure, CI/CD, and real-time clustering.",
    sharedMedia: [
      { id: "m5-1", name: "sla-dashboard-export.csv", type: "file", size: "320 KB", date: "Sep 16, 2026" },
    ],
    messages: [
      {
        id: "msg-5-1",
        senderId: "contact-5",
        senderName: "Priya Sharma",
        senderAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
        content: "All service monitors are green across US-East and EU-Central.",
        timestamp: "5:00 PM",
        date: "September 16, 2026",
        isSentByMe: false,
        reactions: [{ emoji: "🎉", count: 6 }],
      },
    ],
  },
];

export const initialChannels: Channel[] = [
  {
    id: "ch-announcements",
    name: "announcements",
    description: "Official company news, product launches, and company-wide milestones.",
    category: "General",
    isPrivate: false,
    subscriberCount: 342,
    isJoined: true,
  },
  {
    id: "ch-engineering",
    name: "engineering-core",
    description: "Real-time sync, distributed infrastructure, APIs, and performance.",
    category: "Engineering",
    isPrivate: false,
    subscriberCount: 184,
    isJoined: true,
  },
  {
    id: "ch-design",
    name: "design-systems",
    description: "Tailwind tokens, shadcn components, accessibility, and UX guidelines.",
    category: "Design",
    isPrivate: false,
    subscriberCount: 96,
    isJoined: true,
  },
  {
    id: "ch-product",
    name: "product-strategy",
    description: "Roadmaps, quarterly OKRs, competitor analysis, and feature brainstorming.",
    category: "Product",
    isPrivate: false,
    subscriberCount: 120,
    isJoined: false,
  },
  {
    id: "ch-ai-research",
    name: "ai-copilot-labs",
    description: "Exploring agentic workflows, conversational intelligence, and streaming models.",
    category: "Engineering",
    isPrivate: false,
    subscriberCount: 215,
    isJoined: false,
  },
  {
    id: "ch-random",
    name: "watercooler-chat",
    description: "Casual banter, pet pictures, coffee recipes, and weekend hobbies.",
    category: "Random",
    isPrivate: false,
    subscriberCount: 289,
    isJoined: true,
  },
  {
    id: "ch-security-audits",
    name: "security-compliance",
    description: "End-to-end encryption specs, SOC2 compliance, and vulnerability triage.",
    category: "Engineering",
    isPrivate: true,
    subscriberCount: 42,
    isJoined: false,
  },
  {
    id: "ch-user-feedback",
    name: "customer-insights",
    description: "Direct customer feedback feeds, NPS surveys, and feature request tracking.",
    category: "Product",
    isPrivate: false,
    subscriberCount: 78,
    isJoined: false,
  },
];
